[package]
name = "rust-video-editor-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "console",
    "Document", 
    "Element",
    "HtmlElement",
    "HtmlVideoElement",
    "HtmlCanvasElement",
    "WebGlRenderingContext",
    "WebGl2RenderingContext",
    "Performance",
    "Window",
    "Worker",
    "WorkerGlobalScope",
    "MessageEvent",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "VideoFrame",
    "VideoEncoder",
    "VideoDecoder",
    "EncodedVideoChunk",
    "VideoEncoderConfig",
    "VideoDecoderConfig"
]}
wgpu = { version = "0.17", features = ["webgl"] }
bytemuck = "1.14"

[features]
default = ["wee_alloc"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1